CITIES = [
    ("Tunis", "Tunis"),
    ("Sfax", "Sfax"),
    ("Sousse", "Sousse"),
    ("Ettadhamen", "Ettadhamen"),
    ("Kairouan", "Kairouan"),
    ("Gabès", "Gabès"),
    ("Bizerte", "Bizerte"),
    ("Ariana", "Ariana"),
    ("Gafsa", "Gafsa"),
    ("Monastir", "Monastir"),
    ("Médenine", "Médenine"),
    ("Beja", "Beja"),
    ("Jendouba", "Jendouba"),
    ("Nabeul", "Nabeul"),
    ("Kasserine", "Kasserine"),
    ("Sidi Bouzid", "Sidi Bouzid"),
    ("Tozeur", "Tozeur"),
    ("Siliana", "Siliana"),
    ("Tataouine", "Tataouine"),
    ("Kebili", "Kebili"),
    ("Ben Arous", "Ben Arous"),
    ("Mahdia", "Mahdia"),
    ("Manouba", "Manouba"),
    ("Zaghouan", "Zaghouan"),
    ("Kef", "Kef"),
    ("Moknine", "Moknine"),
    ("Menzel Temime", "Menzel Temime"),
]
