# Generated by Django 4.1 on 2024-06-18 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="supplier",
            name="appearance",
            field=models.CharField(
                choices=[("Petite", "Petite"), ("Grande", "Grande")],
                default="Petite",
                max_length=10,
            ),
        ),
    ]
