from app.cms.admin.BlogAdmin import BlogAdmin
from app.cms.admin.BlogSectionAdmin import BlogSectionAdmin
from app.cms.admin.BlogTagAdmin import BlogTagAdmin
from app.cms.admin.BlogThematicAdmin import BlogThematicAdmin
from app.cms.admin.FAQQuestionAdmin import FAQQuestionAdmin
from app.cms.admin.FAQThematicAdmin import FAQThematicAdmin
from app.cms.admin.GuideArticleAdmin import GuideArticleAdmin
from app.cms.admin.GuideSectionAdmin import GuideSectionAdmin
from app.cms.admin.GuideThematicAdmin import GuideThematicAdmin
from app.cms.admin.PrivacyPolicyAdmin import PrivacyPolicyAdmin
from app.cms.admin.TermsAndConditionsAdmin import TermsAndConditionsAdmin
from app.cms.admin.CGUCGVPolicyAdmin import CGUCGVPolicyAdmin
from app.cms.admin.CookiesPolicyAdmin import CookiesPolicyAdmin
