ACCEPTED = "Accepted"
REFUSED = "Refused"
INTERESTED = "Interested"
SELECTION_STATUS_CHOICES = [
    (ACCEPTED, ACCEPTED),
    (REFUSED, REFUSED),
    (INTERESTED, INTERESTED),
]


DISCUSSION = 'Discussion'
QUOTES = 'Quotes'
DECISION = 'Decision'

# Choices for the phase names
PHASE_NAME_CHOICES = [
    (DISCUSSION, DISCUSSION),
    (QUOTES, QUOTES),
    (DECISION, DECISION),
]