name: Django CI

on:
  push:
    branches:
      - dev # Trigger CI on push to the dev branch
  # pull_request:
  #   branches:
  #     - main # Uncomment this to enable PR checks for main branch

jobs:
  install-dependencies:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python version
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Create and start virtual environment
        run: |
          python -m venv venv
          source venv/bin/activate

      - name: Install dependencies
        run: |
          source venv/bin/activate
          python -m pip install --upgrade pip
          pip install -r requirements.txt

  lint:
    runs-on: ubuntu-latest
    needs: install-dependencies  # Ensures this job runs after install-dependencies
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python version
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Create and start virtual environment
        run: |
          python -m venv venv
          source venv/bin/activate

      - name: Install dependencies
        run: |
          source venv/bin/activate
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run linters (flake8, isort, black) in virtual environment
        run: |
          source venv/bin/activate  # Activate virtual environment
          # Ensure the environment is activated and tools are available
          which flake8
          which isort
          which black

          # Run the linting tools with the current directory as the target
          flake8 .
          isort --check-only --diff .
          black --check .
